# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2026-06-05 09:52:50

Reproducibility notes:
- Trains RTDETRV2 object detection models with batch sizes 16, 32, and 64.
- Required input: training samples exported from ArcGIS Pro's
  "Export Training Data For Deep Learning" tool.
- Outputs: timestamped model folders under MODEL_OUTPUT_ROOT.
- Before running, set the configuration variables below with environment
  variables or edit the defaults for your local project.
"""
import datetime
import os
from pathlib import Path

import arcpy

# Configurable paths. Environment variables take precedence over defaults.
PROJECT_ROOT = Path(os.environ.get("PROJECT_ROOT", Path.cwd()))
TRAINING_SAMPLES_DIR = Path(
    os.environ.get(
        "TRAINING_SAMPLES_DIR",
        PROJECT_ROOT / "training_data_exports" / "peaches_training_samples",
    )
)
WORKSPACE_GDB = Path(
    os.environ.get("WORKSPACE_GDB", PROJECT_ROOT / "workspace.gdb")
)
MODEL_OUTPUT_ROOT = Path(
    os.environ.get("MODEL_OUTPUT_ROOT", PROJECT_ROOT / "model_outputs")
)
IMAGE_ANALYST_TOOLBOX = os.environ.get("IMAGE_ANALYST_TOOLBOX")
_RUN_STAMP = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")


def _make_out_folder(name: str) -> str:
    out = MODEL_OUTPUT_ROOT / f"{name}_{_RUN_STAMP}"
    out.parent.mkdir(parents=True, exist_ok=True)
    return str(out)


def _image_analyst_toolbox() -> str:
    """Resolve the ArcGIS Image Analyst toolbox without a local install path."""
    if IMAGE_ANALYST_TOOLBOX:
        return IMAGE_ANALYST_TOOLBOX

    install_dir = Path(arcpy.GetInstallInfo()["InstallDir"])
    return str(
        install_dir
        / "Resources"
        / "ArcToolbox"
        / "toolboxes"
        / "Image Analyst Tools.tbx"
    )


def JuicePaperNetworkTest():  # JuicePaperNetworkTest

    # Allow overwriting outputs; each experiment still gets its own unique folder.
    arcpy.env.overwriteOutput = True

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("ImageExt")
    arcpy.CheckOutExtension("ImageAnalyst")

    arcpy.ImportToolbox(_image_analyst_toolbox())
    peaches_training_samples = str(TRAINING_SAMPLES_DIR)
    peaches_training_samples_2_ = str(TRAINING_SAMPLES_DIR)
    peaches_training_samples_3_ = str(TRAINING_SAMPLES_DIR)

    # Process: Train Deep Learning Model (TrainDeepLearningModel) (ia)
    Train_DL_Model_Results = _make_out_folder("Train_DL_Model_Results_bs16")
    peaches_training_samples_DLmodel_dlpk = arcpy.ia.TrainDeepLearningModel(
        in_folder=[peaches_training_samples],
        out_folder=Train_DL_Model_Results,
        max_epochs=100,
        model_type="RTDETRV2",
        batch_size=16,
        arguments=[],
        learning_rate=0.0003,
        backbone_model="RESNET101",
        stop_training="CONTINUE_TRAINING",
        freeze="UNFREEZE_MODEL",
        chip_size=256,
        weight_init_scheme="ALL_RANDOM",
    )[0]

    # Process: Train Deep Learning Model (2) (TrainDeepLearningModel) (ia)
    Train_DL_Model_Results_3_ = _make_out_folder("Train_DL_Model_Results_bs32")
    if peaches_training_samples_DLmodel_dlpk:
        peaches_training_samples_DLmodel_dlpk_3_ = arcpy.ia.TrainDeepLearningModel(
            in_folder=[peaches_training_samples_2_],
            out_folder=Train_DL_Model_Results_3_,
            max_epochs=100,
            model_type="RTDETRV2",
            batch_size=32,
            arguments=[],
            learning_rate=0.0003,
            backbone_model="RESNET101",
            stop_training="CONTINUE_TRAINING",
            freeze="UNFREEZE_MODEL",
            chip_size=256,
            weight_init_scheme="ALL_RANDOM",
        )[0]

    # Process: Train Deep Learning Model (3) (TrainDeepLearningModel) (ia)
    Train_DL_Model_Results_4_ = _make_out_folder("Train_DL_Model_Results_bs64")
    if peaches_training_samples_DLmodel_dlpk and peaches_training_samples_DLmodel_dlpk_3_:
        peaches_training_samples_DLmodel_dlpk_4_ = arcpy.ia.TrainDeepLearningModel(
            in_folder=[peaches_training_samples_3_],
            out_folder=Train_DL_Model_Results_4_,
            max_epochs=100,
            model_type="RTDETRV2",
            batch_size=64,
            arguments=[],
            learning_rate=0.0003,
            backbone_model="RESNET101",
            stop_training="CONTINUE_TRAINING",
            freeze="UNFREEZE_MODEL",
            chip_size=256,
            weight_init_scheme="ALL_RANDOM",
        )[0]


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(
        scratchWorkspace=str(WORKSPACE_GDB),
        workspace=str(WORKSPACE_GDB),
    ):
        JuicePaperNetworkTest()
