# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2026-06-05 09:52:50
"""
from pathlib import Path
import datetime
import arcpy

_BASE_OUT = Path(r"C:\Users\gcpost\Documents\ArcGIS\Projects\PeachGeoAI")
_RUN_STAMP = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")


def _make_out_folder(name: str) -> str:
    out = _BASE_OUT / f"{name}_{_RUN_STAMP}"
    out.parent.mkdir(parents=True, exist_ok=True)
    return str(out)


def JuicePaperNetworkTest():  # JuicePaperNetworkTest

    # Allow overwriting outputs; each experiment still gets its own unique folder.
    arcpy.env.overwriteOutput = True

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("ImageExt")
    arcpy.CheckOutExtension("ImageAnalyst")

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Image Analyst Tools.tbx")
    peaches_training_samples = r"H:\CCIT\CCGT\Projects\PeachGeoAI\PeachGeoAI_Spring2026\Peach_GeoAI\Training_Data_Exports\peaches_training_samples"
    peaches_training_samples_2_ = r"H:\CCIT\CCGT\Projects\PeachGeoAI\PeachGeoAI_Spring2026\Peach_GeoAI\Training_Data_Exports\peaches_training_samples"
    peaches_training_samples_3_ = r"H:\CCIT\CCGT\Projects\PeachGeoAI\PeachGeoAI_Spring2026\Peach_GeoAI\Training_Data_Exports\peaches_training_samples"

    # Process: Train Deep Learning Model (TrainDeepLearningModel) (ia)
    Train_DL_Model_Results = _make_out_folder("Train_DL_Model_Results_bs16")
    peaches_training_samples_DLmodel_dlpk = arcpy.ia.TrainDeepLearningModel(
        in_folder=[peaches_training_samples],
        out_folder=Train_DL_Model_Results,
        max_epochs=100,
        model_type="RTDETRV2",
        batch_size=16,
        arguments=[],
        learning_rate=0.0003,
        backbone_model="RESNET101",
        stop_training="CONTINUE_TRAINING",
        freeze="UNFREEZE_MODEL",
        chip_size=256,
        weight_init_scheme="ALL_RANDOM",
    )[0]

    # Process: Train Deep Learning Model (2) (TrainDeepLearningModel) (ia)
    Train_DL_Model_Results_3_ = _make_out_folder("Train_DL_Model_Results_bs32")
    if peaches_training_samples_DLmodel_dlpk:
        peaches_training_samples_DLmodel_dlpk_3_ = arcpy.ia.TrainDeepLearningModel(
            in_folder=[peaches_training_samples_2_],
            out_folder=Train_DL_Model_Results_3_,
            max_epochs=100,
            model_type="RTDETRV2",
            batch_size=32,
            arguments=[],
            learning_rate=0.0003,
            backbone_model="RESNET101",
            stop_training="CONTINUE_TRAINING",
            freeze="UNFREEZE_MODEL",
            chip_size=256,
            weight_init_scheme="ALL_RANDOM",
        )[0]

    # Process: Train Deep Learning Model (3) (TrainDeepLearningModel) (ia)
    Train_DL_Model_Results_4_ = _make_out_folder("Train_DL_Model_Results_bs64")
    if peaches_training_samples_DLmodel_dlpk and peaches_training_samples_DLmodel_dlpk_3_:
        peaches_training_samples_DLmodel_dlpk_4_ = arcpy.ia.TrainDeepLearningModel(
            in_folder=[peaches_training_samples_3_],
            out_folder=Train_DL_Model_Results_4_,
            max_epochs=100,
            model_type="RTDETRV2",
            batch_size=64,
            arguments=[],
            learning_rate=0.0003,
            backbone_model="RESNET101",
            stop_training="CONTINUE_TRAINING",
            freeze="UNFREEZE_MODEL",
            chip_size=256,
            weight_init_scheme="ALL_RANDOM",
        )[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(
        scratchWorkspace=r"C:\Users\gcpost\Documents\ArcGIS\Projects\PeachGeoAI\PeachGeoAI.gdb",
        workspace=r"C:\Users\gcpost\Documents\ArcGIS\Projects\PeachGeoAI\PeachGeoAI.gdb",
    ):
        JuicePaperNetworkTest()
